version: "2"
services:
  redis:
    image: redis
    ports:
      - 32770:6379
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
  default:
    external:
      name: default-network
      
