#dev 
version: "2"
services:
#  wgmApi:
#    container_name: wgmAPI
#    depends_on:
#       - es
#       - cache
#       - db
#    build: .
#    restart: always
#    depends_on:
#      - redis
#    links:
#      - redis
#    ports:
#      - 8081:9550
#    volumes:
#      - "./public:/var/app/public"
  redis:
    container_name: wgm_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /Users/Shared/RedisData:/var/lib/data/db
    environment:
      - REDIS_USER=root
      - REDIS_ROOT_PASSWORD=111111
      - /Users/Shared/RedisData:/var/lib/data/db
  mongo:
    container_name: wgm_mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/Shared/MonngoData:/var/lib/data/db
    environment:
      - MONGO_USER=root
      - MONGODB_ROOT_PASSWORD=111111
      - MONGODB_DATABASE=wgm
      - /Users/Shared/MonngoData:/var/lib/data/db

#  postgres:
#    container_name: wgm_postgres
#    image: postgres
#    ports:
#      - 5451:5432
#    volumes:
#      - /Users/Shared/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=111111
#      - /Users/Shared/data:/var/lib/postgresql/data
    networks:
      default:
        external:
          name: default-network
